# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 16:35
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180914_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='label_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://10.1.62.101/media/quiz/label/', location='C:\\Users\\Underwood\\PycharmProjects\\annotation\\media\\quiz\\label'), upload_to=quizzes.models.upload_quiz_file_path),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://10.1.62.101/media/quiz/', location='C:\\Users\\Underwood\\PycharmProjects\\annotation\\media\\quiz'), upload_to=quizzes.models.upload_quiz_file_path),
        ),
    ]
