# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 21:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=tasks.models.upload_image_file_path)),
                ('label', models.CharField(blank=True, choices=[('猫', 'cat'), ('狗', 'dog')], max_length=128, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TextClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/eli/django_projects/annotatation/media_root'), upload_to=tasks.models.upload_text_file_path)),
                ('label', models.CharField(blank=True, choices=[('政治', 'political'), ('体育', 'sport')], max_length=128, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
