# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180418_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageclassification',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AlterField(
            model_name='imageclassification',
            name='label',
            field=models.CharField(blank=True, choices=[('猫', 'cat'), ('狗', 'dog')], default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textclassification',
            name='label',
            field=models.CharField(blank=True, choices=[('政治', 'political'), ('体育', 'sport')], default='', max_length=128),
            preserve_default=False,
        ),
    ]
