# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180911_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributor',
        ),
    ]
