# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180419_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageclassification',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='textclassification',
            old_name='update',
            new_name='updated',
        ),
    ]
