# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
