# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 15:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180911_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.AddField(
            model_name='task',
            name='contributor',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
