# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspected_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_task', to='tasks.Task'),
        ),
    ]
