# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_check_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_task', to='tasks.Task'),
        ),
    ]
