# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_check_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_task', to='tasks.Task'),
        ),
    ]
