# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20180913_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributor_char',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_char',
        ),
        migrations.RemoveField(
            model_name='task',
            name='label_char',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_char',
        ),
    ]
