# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20180914_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
