# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180910_1420'),
        ('tasks', '0018_auto_20180914_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
