# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20180914_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
