# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='committed',
            field=models.BooleanField(default=False),
        ),
    ]
