# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20180919_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='committed',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='committed',
        ),
        migrations.AddField(
            model_name='contribution',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
