# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 21:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('TextClassification', '文本分类'), ('ImageClassification', '图像分类')], max_length=128)),
                ('description', models.TextField(blank=True)),
                ('project_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/eli/django_projects/annotation/media_root'), upload_to=projects.models.upload_project_file_path)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_projects', to=settings.AUTH_USER_MODEL)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
