# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 14:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed_project', max_length=128)),
                ('contributors_char', models.CharField(blank=True, default='', max_length=255)),
                ('accuracy_requirement', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('repetition_rate', models.DecimalField(decimal_places=1, default=1.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('project_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Underwood\\PycharmProjects\\annotation\\media'), upload_to=projects.models.upload_project_file_path)),
                ('is_file_changed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/result/', location='C:\\Users\\Underwood\\PycharmProjects\\annotation\\result'), upload_to='')),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_projects', to=settings.AUTH_USER_MODEL)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founded_projects', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspected_projects', to=settings.AUTH_USER_MODEL)),
                ('project_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_projects', to='quizzes.QuestionType')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_projects', to='quizzes.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('project_status', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('project_status_name', models.CharField(max_length=128)),
                ('verify_status', models.CharField(max_length=128)),
                ('verify_status_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_projects', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='verify_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
