# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default='unreleased', on_delete=django.db.models.deletion.CASCADE, to='projects.Status'),
        ),
    ]
