# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180910_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='id',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
