# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 16:35
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180917_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='result_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://10.1.62.101/result/', location='C:\\Users\\Underwood\\PycharmProjects\\annotation\\result'), upload_to=''),
        ),
    ]
