# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180703_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_status',
            field=models.BooleanField(default=False),
        ),
    ]
