# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180704_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors_char',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
