# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='final_grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='total_good_labels',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='total_labels',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='updated',
        ),
    ]
